#!/bin/bash
#
#PBS -N structure
#PBS -M YOU@ufl.edu
#PBS -m abe
#PBS -o structure.$PBS_JOBID.out
#PBS -e structure.$PBS_JOBID.err
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1gb
#PBS -l walltime=00:05:00
#

#Change to the directory where the job was launched from
cd $PBS_O_WORKDIR

#Use modules to load the environment for structure
module load structure

#Run structure using the structure command line from documentation.
structure -i StructureDubius -m mainparams5M -e extraparams 
