#!/bin/bash
#
#PBS -N velvet
#PBS -M YOU@ufl.edu
#PBS -m abe
#PBS -o velvet.test.out
#PBS -e velvet.test.err
#PBS -l nodes=1:ppn=4
#PBS -l pmem=900mb
#PBS -l walltime=00:05:00
#

cd $PBS_O_WORKDIR
pwd
date

module load velvet

#Get things ready to use threaded (OMP) version of Velvet
#Set OMP_THREAD_LIMIT--should be the same as ppn above
export OMP_THREAD_LIMIT=4
 
#Set OMP_NUM_THREADS--should be 1 lower than ppn 
export OMP_NUM_THREADS=3

mkdir test_run_kmer51
velveth_max99_OMP test_run_kmer51/ 51 -fastq -short /project/bio/training/2012-03-01//filtered.100K.fastq
velvetg_max99_OMP test_run_kmer51/ -min_contig_lgth 500
